In [1]:
import numpy as np

In [7]:
x = np.array([1,2,3,4]) # Создание array`а из листа
x_32 = np.array([1,2,3,4], dtype=np.int32) # Создание array`а с произвольным типом данных

In [5]:
str(x) # array можно легко привести к строке

'[1 2 3 4]'

In [10]:
x.dtype # Тип элементов в массиве

dtype('int64')

In [9]:
x_32.dtype

dtype('int32')

In [11]:
x.shape # Вычисление размерности массива

(4,)

In [13]:
matrix = np.array(
    [[1, 2, 3, 4],
    [2, 3, 4, 5]]
) # Обьявление матрицы

In [19]:
print(matrix)

[[1 2 3 4]
 [2 3 4 5]]


In [15]:
matrix.shape

(2, 4)

In [17]:
array_of_ones = np.ones(5) # Массив, заполненный еденицами
array_of_zeros = np.zeros(5) # Массив, заполненный нулями

In [18]:
diagonale_matrix = np.eye(6) # Матрица, заполненная нулями и имеющая еденицу по диагонали
print(diagonale_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [26]:
random_array = np.random.random((4,4)) # Массив случайных чисел размерности 4:4
print(random_array)

[[0.48735257 0.80604809 0.16278567 0.37727993]
 [0.0743015  0.09594067 0.78666669 0.61156725]
 [0.61884162 0.47052185 0.07931499 0.28319137]
 [0.568559   0.80040014 0.99455449 0.16404736]]


In [27]:
print(x[1]) # Получение обьекта из массива
print(random_array[1,1]) # Получение обьекта из двумерной матрицы
print(random_array[:, :3]) # Слайсинг тоже работает: получаем первые три столбца каждой строки

2
0.09594067378575932
[[0.48735257 0.80604809 0.16278567]
 [0.0743015  0.09594067 0.78666669]
 [0.61884162 0.47052185 0.07931499]
 [0.568559   0.80040014 0.99455449]]


In [28]:
random_array > 0.5 # Создание маски - идентичной по размерам матрицы с True/False по логическому выражению

array([[False,  True, False, False],
       [False, False,  True,  True],
       [ True, False, False, False],
       [ True,  True,  True, False]])

In [29]:
random_array[random_array > 0.5] # Получение элементов по маске

array([0.80604809, 0.78666669, 0.61156725, 0.61884162, 0.568559  ,
       0.80040014, 0.99455449])

In [31]:
matrix.flatten() # Преобразование матрицы к одномерному массиву

array([1, 2, 3, 4, 2, 3, 4, 5])

In [32]:
matrix.T # Транспонирование матрицы

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [35]:
matrix.reshape((8, 1)) # Изменение размера матрицы/массива

array([[1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [4],
       [5]])

In [41]:
v_1 = np.array([9, 10])
v_2 = np.array([11, 12])

In [37]:
v_1 + v_2 # Массивы одного размера умеют в поэлементные арифметические операции

array([20, 22])

In [42]:
np.dot(v_1, v_2) # Скалярное произведение двух векторов

10

In [40]:
matrix = np.array(
    [
        [3, 3, 3],
        [1, 3, 4],
        [7, 1, 3]
    ]
)
print(np.unique(matrix)) # Поиск уникальных элементов в матрице

[1 3 4 7]


In [44]:
m1 = np.array(
    [
        [0, 9, 19, 13],
        [1, 20, 5, 13],
        [12, 11, 3, 4]
    ]
)

m2 = np.array(
    [
        [2, 0, 0, 0],
        [1, 2, 2, 0],
        [2, 1, 1, 0],
        [0, 0, 1, 1]
    ]
)

In [47]:
print(np.diagonal(
    np.dot(
        m1, m2
    )
)) # Поиск элементов на диагонали

[47 45 29]


In [49]:
b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])
print(b.mean()) # Вычисление среднего значения элементов массива

4.875
