In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4]) # Создание array`а из листа
x_32 = np.array([1,2,3,4], dtype=np.int32) # Создание array`а с произвольным типом данных

In [3]:
str(x) # array можно легко привести к строке

'[1 2 3 4]'

In [4]:
x.dtype # Тип элементов в массиве

dtype('int64')

In [5]:
x_32.dtype

dtype('int32')

In [6]:
x.shape # Вычисление размерности массива

(4,)

In [7]:
matrix = np.array(
    [[1, 2, 3, 4],
    [2, 3, 4, 5]]
) # Обьявление матрицы

In [8]:
print(matrix)

[[1 2 3 4]
 [2 3 4 5]]


In [9]:
matrix.shape

(2, 4)

In [10]:
array_of_ones = np.ones(5) # Массив, заполненный еденицами
array_of_zeros = np.zeros(5) # Массив, заполненный нулями

In [11]:
diagonale_matrix = np.eye(6) # Матрица, заполненная нулями и имеющая еденицу по диагонали
print(diagonale_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [12]:
random_array = np.random.random((4,4)) # Массив случайных чисел размерности 4:4
print(random_array)

[[0.57591641 0.13200847 0.4320289  0.14782807]
 [0.9740623  0.92690924 0.55665595 0.56846535]
 [0.66598325 0.51635074 0.43961573 0.41694907]
 [0.31319046 0.28351153 0.12688929 0.67627642]]


In [13]:
print(x[1]) # Получение обьекта из массива
print(random_array[1,1]) # Получение обьекта из двумерной матрицы
print(random_array[:, :3]) # Слайсинг тоже работает: получаем первые три столбца каждой строки

2
0.9269092417078276
[[0.57591641 0.13200847 0.4320289 ]
 [0.9740623  0.92690924 0.55665595]
 [0.66598325 0.51635074 0.43961573]
 [0.31319046 0.28351153 0.12688929]]


In [14]:
random_array > 0.5 # Создание маски - идентичной по размерам матрицы с True/False по логическому выражению

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False,  True]])

In [15]:
random_array[random_array > 0.5] # Получение элементов по маске

array([0.57591641, 0.9740623 , 0.92690924, 0.55665595, 0.56846535,
       0.66598325, 0.51635074, 0.67627642])

In [16]:
matrix.flatten() # Преобразование матрицы к одномерному массиву

array([1, 2, 3, 4, 2, 3, 4, 5])

In [17]:
matrix.T # Транспонирование матрицы

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [18]:
matrix.reshape((8, 1)) # Изменение размера матрицы/массива

array([[1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [4],
       [5]])

In [19]:
v_1 = np.array([9, 10])
v_2 = np.array([11, 12])

In [20]:
v_1 + v_2 # Массивы одного размера умеют в поэлементные арифметические операции

array([20, 22])

In [21]:
np.dot(v_1, v_2) # Скалярное произведение двух векторов

219

In [22]:
matrix = np.array(
    [
        [3, 3, 3],
        [1, 3, 4],
        [7, 1, 3]
    ]
)
print(np.unique(matrix)) # Поиск уникальных элементов в матрице

[1 3 4 7]


In [23]:
m1 = np.array(
    [
        [0, 9, 19, 13],
        [1, 20, 5, 13],
        [12, 11, 3, 4]
    ]
)

m2 = np.array(
    [
        [2, 0, 0, 0],
        [1, 2, 2, 0],
        [2, 1, 1, 0],
        [0, 0, 1, 1]
    ]
)

In [24]:
print(np.diagonal(
    np.dot(
        m1, m2
    )
)) # Поиск элементов на диагонали

[47 45 29]


In [25]:
b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])
print(b.mean()) # Вычисление среднего значения элементов массива

4.875
